[package]
name = "pid"
version = "0.1.0"
authors = ["yarkw <contact@yarkw.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
